[phases]
  install = "python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"
  start = "flask run --host=0.0.0.0 --port=${PORT}"

[variables]
  PORT = "8000"
